packages:
  - packages/*

catalog:
  "@types/node": ^25.5.2
  "@typescript-eslint/parser": ^8.58.1
  "@typescript-eslint/typescript-estree": ^8.58.1
  eslint: ^9.39.4
  eslint-vitest-rule-tester: ^3.1.0
  oxlint: 1.70.0
  publint: ^0.3.18
  typescript: ^6.0.2
  vite-plus: 0.2.1
  vitest: 4.1.9

onlyBuiltDependencies:
  - esbuild
