packages:
  - packages/*

catalog:
  "@types/node": ^26.6.2
  "@typescript-eslint/parser": ^8.70.0
  "@typescript-eslint/typescript-estree": ^8.70.0
  eslint: ^10.11.0
  eslint-vitest-rule-tester: ^3.2.0
  fs-fixture: ^2.16.0
  oxlint: 1.83.0
  publint: ^0.3.24
  typescript: ^6.0.3
  unplugin-unused: ^0.6.0
  vite-plus: 0.2.3
  vitest: 4.1.9

onlyBuiltDependencies:
  - esbuild
