# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  push:
  pull_request:

jobs:
  check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          github_access_token: ${{ github.token }}
      - run: nix develop --command vp install --frozen-lockfile
      - run: nix develop --command vp run check
      - run: nix develop --command vp run test
      - run: nix fmt -- --fail-on-change
      - run: nix flake check

  pkg-pr-new:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          github_access_token: ${{ github.token }}
      - run: nix develop --command vp install --frozen-lockfile
      - run: nix develop --command vp exec pkg-pr-new publish './packages/*' --pnpm
