# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  push:
  pull_request:

jobs:
  check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          github_access_token: ${{ github.token }}
      - run: nix develop --command vp install --frozen-lockfile
      - run: nix develop --command vp run check
      - run: nix develop --command vp run -r typecheck
      - run: nix develop --command vp run -r test
      - run: nix fmt -- --fail-on-change
      - run: nix flake check

  pkg-pr-new:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          github_access_token: ${{ github.token }}
      - run: nix develop --command vp install --frozen-lockfile
      - run: nix develop --command vp exec pkg-pr-new publish './packages/*' --pnpm
